# Generated by Django 4.2.7 on 2023-12-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(default=None, max_length=250, null=True, upload_to='servicesImage/')),
                ('paragraph', models.TextField(max_length=10000, null=True)),
            ],
        ),
    ]
