# Generated by Django 4.2.7 on 2023-12-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carCounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200, null=True)),
                ('file', models.FileField(default=None, max_length=200, null=True, upload_to='carCounterFile/')),
            ],
        ),
    ]
