# Generated by Django 4.2.7 on 2023-12-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carCounting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carCounting',
        ),
    ]
