# Generated by Django 4.2.7 on 2023-12-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
