# Generated by Django 4.2.7 on 2023-12-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0004_alter_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
