# Generated by Django 4.2.7 on 2023-12-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0005_remove_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
